### ISSUE TITLE
Permit arithmetic

### ISSUE THREAD

**Issue by asomers** [nathdobson/async-weighted-semaphore#1]
Your crate is very close to what I need.  However, I need one thing more: the ability to add and subtract permits.  For example, I need to be able to acquire a `SemaphoreGuard` with 10 permits and another with 5, then combine them into a single `SemaphoreGuard` with 15.  I also need to be able to do the reverse: split a single `SemaphoreGuard` into two, with a selectable division of permits between them.  Do you think this feature would be a useful addition to your library?  If so, I'll try to add it.

**Comment by nathdobson** [comment]
Are `SemaphoreGuard::forget` and `SemaphoreGuard::new` sufficient? Or is it valuable to have built-in helper methods specifically for combining/splitting?

```
fn combine_guards<'a>(
    sem: &'a Semaphore,
    g1: SemaphoreGuard<'a>,
    g2: SemaphoreGuard<'a>)
    -> SemaphoreGuard<'a> {
    SemaphoreGuard::new(sem, g1.forget() + g2.forget())
}

fn split_guard<'a>(
    sem: &'a Semaphore,
    g: SemaphoreGuard<'a>,
    permits: usize)
    -> (SemaphoreGuard<'a>, SemaphoreGuard<'a>) {
    (SemaphoreGuard::new(sem, g.forget() - permits),
     SemaphoreGuard::new(sem, permits))
}
```

**Comment by asomers** [comment]
Yes, the `forget` and `new` methods could work.  However, they aren't safe; they make it easy to destroy or create permits.  Dedicated `combine` and `split` methods would be better, since they would conserve the number of permits.

**Comment by nathdobson** [comment]
Adding methods SGTM. A few thoughts:

Should the methods take `self` or `&mut self`? I would expect `&mut self` to be slightly more generic for cases where a `SemaphoreGuard` is stored in a field instead of a local.

Errors need to be handled carefully:
- Combining `SemaphoreGuard`s from different semaphores. Maybe just panic?
- Overflow from combining too many permits. I would expect poisoning on drop without panicking.
- Underflow from splitting too many permits. This could return an Err, or just panic.

Do existing names like `extend`/`split_off` from `Vec` make sense here?

**Comment by asomers** [comment]
Is it necessary to provide the Semaphore as an argument to `combine_guards`?  It might not be readily available.  I'm thinking of an api like this:
```rust
/// consumes another guard, adding its permits to our own.
///
/// On overflow or other error, returns the supplied guard rather than consuming it.
fn extend(self: &SemaphoreGuardArc, other: SemaphoreGuardArc) -> Result<(), SemaphoreGuardArc> {...}
/// Creates a new guard for the same Semaphore.  The original will return `at` permits, and the new guard will have whatever's left.
///
/// Returns `Err(())` if the new would guard would have 0 or fewer permits.
fn split_off(self: &SemaphoreGuardArc, at: usize) -> Result<SemaphoreGuardArc, ()> { ...}
```
As far as combining guard from different semaphores, I don't have a strong feeling there.  I intend to use just a single Semaphore in my application, so panicing would be fine with me.  If you need something fancier it would probably be best to define your own error types.

**Comment by nathdobson** [comment]
There's no need to provide the semaphore. I just showed that as an example for writing the methods outside the crate using the existing API.

Don't the methods need to take `&mut self`, instead of `&self` to alter the `amount` field?

Is there a reason you want a `Result` from `extend` instead of poisoning? For overflow `release` poisons the semaphore and lets the caller of `acquire` handle the error. Do you have a way to recover from overflow after `extend` in your use case? 

`split_off` should have a custom error type, so that the error message is more specific than "()". I also realized that `split_off` might be backwards: I would expect it to return a requested number of permits instead of leaving that many behind and returning the remainder.

**Comment by asomers** [comment]
Yes, they should take `&mut self`.  Changing the meaning of `split_off`'s argument makes sense too, but then we should rename it so it won't be confused with `Vec::split_off`.  Maybe `split(&self, permits: usize)`?

As for error handling in `extend`, I just realized something.  The only reason there would be an overflow is if the two Guards' permit counts combined exceeded the Semaphore's maximum, right?  If that's true, there shouldn't be any way to create such guards.  So it's fine to panic in that case.

**Comment by nathdobson** [comment]
`split` SGTM.

Overflow will be uncommon. Signaling semaphores will probably immediately forget any acquired permits without performing arithmetic. Guarding semaphores will be fine unless the caller uses `new`/`forget` incorrectly. However for consistency with the existing API it's worth poisoning instead of panicking.
